# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Animated Movies Make Me Cry' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Animated Movies Make Me Cry
  pod 'Firebase'

  target 'Animated Movies Make Me CryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Animated Movies Make Me CryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
